

import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavbarComponent from "@/layouts/navbar";
import FooterComponent from "@/layouts/footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <NavbarComponent/>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
